param(
    [string]$OutPath = "tools/v3_baseline/baseline_lock.json",
    [int]$SponzaN = 2048,
    [ValidateSet("PENDING", "CONVERGED", "MARGINAL", "PROVISIONAL")]
    [string]$SponzaVerdict = "PENDING"
)

# Builds a conservative M0 Stage 1 baseline lock.
# Missing files are recorded as missing; this script never fabricates metrics.

function Get-FileRecord {
    param([string]$Path)
    if (Test-Path $Path) {
        $item = Get-Item $Path
        return [ordered]@{
            path = $Path
            status = "present"
            bytes = $item.Length
            sha256 = (Get-FileHash -Algorithm SHA256 $Path).Hash.ToLowerInvariant()
        }
    }
    return [ordered]@{
        path = $Path
        status = "missing"
    }
}

function Get-CaptureRecord {
    param(
        [string]$Tag,
        [string]$Dir,
        [int]$N,
        [object]$Metrics = $null,
        [string]$Source = "generated by v3 M0 Stage 1"
    )

    $files = [ordered]@{
        png = Get-FileRecord "$Dir/$Tag.png"
        cascade_gi = Get-FileRecord "$Dir/${Tag}_cascade_gi.exr"
        pt_full = Get-FileRecord "$Dir/${Tag}_pt_full.exr"
        pt_direct = Get-FileRecord "$Dir/${Tag}_pt_direct.exr"
    }
    $missing = @($files.Values | Where-Object { $_.status -ne "present" }).Count
    $rec = [ordered]@{
        tag = $Tag
        dir = $Dir
        N = $N
        status = if ($missing -eq 0) { "complete" } else { "partial" }
        source = $Source
        files = $files
    }
    if ($Metrics) {
        $rec.metrics = $Metrics
    }
    return $rec
}

function Get-MetricRow {
    param(
        [string]$Path,
        [int]$N
    )
    if (-not (Test-Path $Path)) {
        return $null
    }
    $metrics = Get-Content $Path -Raw | ConvertFrom-Json
    $key = [string]$N
    if ($null -eq $metrics.rows.$key -or $metrics.rows.$key.status -ne "ok") {
        return $null
    }
    return $metrics.rows.$key
}

$postfixJson = "tools/v20_convergence/captures_cv1_postfix/cv1_postfix_results.json"
$cornellMetrics = $null
if (Test-Path $postfixJson) {
    $j = Get-Content $postfixJson -Raw | ConvertFrom-Json
    $m = $j.pre."2048"
    $cornellMetrics = @{
        ratio_self = [double]$m.ratio_self
        abs_p95 = [double]$m.abs_p95
        bright_pct = [double]$m.bright_pct
        dim_pct = [double]$m.dim_pct
        mean_casc = [double]$m.mean_casc
        mean_pt = [double]$m.mean_pt
        valid = [int]$m.valid
    }
}

$cornellOffTag = "cv1_cornell_cam0_mbon_g100_hyb0_N2048_m17_postfix"
$cornellOnTag  = "v3base_cornell_cam0_mbon_g100_hyb1_N2048_m17"
$sponzaOffTag  = "v3base_sponza_cam0_mbon_g100_hyb0_N$('{0:D4}' -f $SponzaN)_m17"
$sponzaOnTag   = "v3base_sponza_cam0_mbon_g100_hyb1_N$('{0:D4}' -f $SponzaN)_m17"
$sponzaOffMetrics = Get-MetricRow "tools/v3_baseline/sponza_default_metrics.json" $SponzaN
$sponzaOnMetrics = Get-MetricRow "tools/v3_baseline/sponza_hybon_metrics.json" $SponzaN

$lock = [ordered]@{
    _note = "M0 Stage 1 baseline lock for v3 ShaderToy adoption. Missing entries are intentional until captures run."
    _locked_at = (Get-Date).ToUniversalTime().ToString("o")
    _engine_build = [ordered]@{
        exe = Get-FileRecord "build/RadianceCascades3D.exe"
        build_id = "3d_v3.0 + EXR capture plumbing cherry-picked from 3d_2.0_fail"
    }
    captures = [ordered]@{
        cornell_cam0_cascade_off = Get-CaptureRecord $cornellOffTag "tools/v20_convergence/captures_cv1_postfix" 2048 $cornellMetrics "reused from v20 cv1_postfix"
        cornell_cam0_hybrid_on = Get-CaptureRecord $cornellOnTag "tools/v3_baseline/captures_cornell_hybon" 2048 $null "captured by tools/v3_baseline/cornell_hybon_capture.ps1"
        sponza_cam0_cascade_off = Get-CaptureRecord $sponzaOffTag "tools/v3_baseline/captures_sponza_default" $SponzaN $sponzaOffMetrics "captured by tools/v3_baseline/sponza_capture.ps1 -UseHybrid 0"
        sponza_cam0_hybrid_on = Get-CaptureRecord $sponzaOnTag "tools/v3_baseline/captures_sponza_hybon" $SponzaN $sponzaOnMetrics "captured by tools/v3_baseline/sponza_capture.ps1 -UseHybrid 1"
    }
    audits = [ordered]@{
        delta3_alpha_audit = [ordered]@{ doc = "tools/v3_baseline/delta3_alpha_audit.md"; verdict = "see doc" }
        delta5_ceiling_estimate = [ordered]@{ doc = "tools/v3_baseline/delta5_ceiling_estimate.md"; verdict = "<3 percent magnitude leverage estimate" }
        delta7_offset_audit = [ordered]@{ doc = "tools/v3_baseline/delta7_offset_audit.md"; verdict = "conformant" }
    }
    sign_off = [ordered]@{
        cornell_N = 2048
        sponza_N = $SponzaN
        sponza_convergence_verdict = $SponzaVerdict
    }
}

$parent = Split-Path $OutPath -Parent
if ($parent -and -not (Test-Path $parent)) {
    New-Item -ItemType Directory -Force $parent | Out-Null
}
$lock | ConvertTo-Json -Depth 12 | Set-Content -Encoding UTF8 $OutPath
Write-Host "wrote $OutPath"
