#!/usr/bin/env python3
"""Generate src/octahedral_solid_angle.h — per-bin solid-angle LUTs (A2 gate).

Uses the same oct_to_dir + finite-difference Jacobian as octahedral_solid_angle.py
(verified: sum(D) ~= 4*pi, hemisphere ~= 2*pi, int cos^+ = pi).  Emits two 256-entry
arrays so the raymarch shader can index uSolidAngleLUT[dy*D+dx] for D in {8,16}.
"""
import math
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "src",
                   "octahedral_solid_angle.h")


def oct_to_dir(uv):
    u = uv[0] * 2.0 - 1.0
    v = uv[1] * 2.0 - 1.0
    d = [u, v, 1.0 - abs(u) - abs(v)]
    if d[2] < 0.0:
        ox, oy = d[0], d[1]
        d[0] = (1.0 - abs(oy)) * (1.0 if ox >= 0.0 else -1.0)
        d[1] = (1.0 - abs(ox)) * (1.0 if oy >= 0.0 else -1.0)
    ln = math.sqrt(d[0] * d[0] + d[1] * d[1] + d[2] * d[2])
    return (d[0] / ln, d[1] / ln, d[2] / ln)


def jacobian(uv, h=1e-5):
    def tangent(axis):
        p = [uv[0], uv[1]]
        m = [uv[0], uv[1]]
        p[axis] += h
        m[axis] -= h
        np_ = oct_to_dir(p)
        nm = oct_to_dir(m)
        return ((np_[0] - nm[0]) / (2.0 * h),
                (np_[1] - nm[1]) / (2.0 * h),
                (np_[2] - nm[2]) / (2.0 * h))
    du = tangent(0)
    dv = tangent(1)
    cr = (du[1] * dv[2] - du[2] * dv[1],
          du[2] * dv[0] - du[0] * dv[2],
          du[0] * dv[1] - du[1] * dv[0])
    return math.sqrt(cr[0] * cr[0] + cr[1] * cr[1] + cr[2] * cr[2])


def lut(D, S=24):
    vals = []
    for dy in range(D):
        for dx in range(D):
            acc = 0.0
            for i in range(S):
                for j in range(S):
                    uv = ((dx + (i + 0.5) / S) / D, (dy + (j + 0.5) / S) / D)
                    acc += jacobian(uv)
            vals.append(acc / (S * S * D * D))
    return vals


def fmt(arr):
    out = []
    for i in range(0, len(arr), 8):
        out.append("    " + ", ".join("%.6ff" % v for v in arr[i:i + 8]) + ",")
    return "\n".join(out)


def main():
    d8 = lut(8)
    d16 = lut(16)
    d8_256 = d8 + [0.0] * (256 - len(d8))

    with open(OUT, "w") as f:
        f.write("// Generated by doc/12_cornell_rc_audit/octahedral_solid_angle_gen.py\n")
        f.write("// Octahedral per-bin solid angle (steradians) for dirToOct/octToDir.\n")
        f.write("// Verified: sum(kOctaSolidAngleD16) ~= 4*pi; D8 hemisphere ~= 2*pi;\n")
        f.write("//           sum_b DeltaOmega_b cos^+_b = pi.\n")
        f.write("#pragma once\n\n")
        f.write("// D=8 LUT (first 64 entries) padded to 256 for uniform-array upload.\n")
        f.write("static const float kOctaSolidAngleD8[256] = {\n")
        f.write(fmt(d8_256))
        f.write("\n};\n\n")
        f.write("// D=16 LUT (256 entries).\n")
        f.write("static const float kOctaSolidAngleD16[256] = {\n")
        f.write(fmt(d16))
        f.write("\n};\n")
    print("wrote", OUT)
    print("D8  sum=%.6f (4pi=%.6f)" % (sum(d8), 4 * math.pi))
    print("D16 sum=%.6f (4pi=%.6f)" % (sum(d16), 4 * math.pi))


if __name__ == "__main__":
    main()
