#!/usr/bin/env python3
"""
Phase 3B: Generate raymarch.frag with included chart classification and probe mapping functions.

This script concatenates shared .glsl include files into raymarch.frag to avoid manual copy-paste.
Usage: python tools/generate_raymarch_with_includes.py

Output: res/shaders/raymarch_generated.frag (use this instead of raymarch.frag in build)
"""

import os
import sys

def read_file(filepath):
    """Read file contents."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(filepath, content):
    """Write content to file."""
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

def generate_raymarch_with_includes():
    """Generate raymarch.frag with included chart classification and probe mapping."""
    
    # Paths
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    shader_dir = os.path.join(base_dir, 'res', 'shaders')
    
    raymarch_path = os.path.join(shader_dir, 'raymarch.frag')
    chart_class_path = os.path.join(shader_dir, 'chart_classification.glsl')
    probe_mapping_path = os.path.join(shader_dir, 'probe_atlas_mapping.glsl')
    output_path = os.path.join(shader_dir, 'raymarch_generated.frag')
    
    # Check input files exist
    for path in [raymarch_path, chart_class_path, probe_mapping_path]:
        if not os.path.exists(path):
            print(f"ERROR: File not found: {path}")
            return False
    
    # Read source files
    print("Reading source files...")
    raymarch_content = read_file(raymarch_path)
    chart_class_content = read_file(chart_class_path)
    probe_mapping_content = read_file(probe_mapping_path)
    
    # Find insertion point (after toneMapACES function, before Main Fragment Shader comment)
    insertion_marker = "// =============================================================================\n// Main Fragment Shader\n// ============================================================================="
    
    if insertion_marker not in raymarch_content:
        print("ERROR: Could not find insertion marker in raymarch.frag")
        return False
    
    # Prepare include content with clear markers
    include_section = """
// =============================================================================
// Phase 3A/3B: Chart Classification & Probe Mapping (auto-generated from includes)
// DO NOT EDIT THIS SECTION - Edit chart_classification.glsl and probe_atlas_mapping.glsl instead
// Generated by: tools/generate_raymarch_with_includes.py
// =============================================================================

""" + chart_class_content + """

""" + probe_mapping_content + """

// =============================================================================
// End of auto-generated section
// =============================================================================

"""
    
    # Insert include content
    parts = raymarch_content.split(insertion_marker)
    if len(parts) != 2:
        print("ERROR: Unexpected format in raymarch.frag")
        return False
    
    generated_content = parts[0] + include_section + insertion_marker + parts[1]
    
    # Write output
    print(f"Writing generated shader to: {output_path}")
    write_file(output_path, generated_content)
    
    print(f"✓ Successfully generated {output_path}")
    print(f"  Original raymarch.frag: {len(raymarch_content)} bytes")
    print(f"  Chart classification: {len(chart_class_content)} bytes")
    print(f"  Probe mapping: {len(probe_mapping_content)} bytes")
    print(f"  Generated output: {len(generated_content)} bytes")
    print(f"\nNOTE: Update your build system to use raymarch_generated.frag instead of raymarch.frag")
    
    return True

if __name__ == "__main__":
    success = generate_raymarch_with_includes()
    sys.exit(0 if success else 1)
