#!/usr/bin/env python3
"""Independent Phase 7 G9 camera-classification fixtures.

Reuses the independent Common.glsl trace port from the Phase 4 generator
(importing it regenerates identical Phase 4 outputs; no duplication of the
trace semantics in a second place). The camera is declared native display
policy; the reference snapshot has no compositor.

Fixtures record, per camera probe pixel: expected hit chart, chartUv,
distance, and sky/hit classification. CPU and GLSL final-view code must agree.
"""
import json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "phase4_transport"))
import generate_transport_golden as t4  # noqa: E402  (independent trace port)

# Native display camera (must match src/reference_camera.cpp exactly).
CAM_POS = (0.5, 0.25, 0.97)
CAM_TARGET = (0.5, 0.25, 0.0)
FOV_Y = 60.0
ASPECT = 4.0 / 3.0

def vsub(a, b): return (a[0]-b[0], a[1]-b[1], a[2]-b[2])
def vnorm(a):
    l = math.sqrt(a[0]*a[0] + a[1]*a[1] + a[2]*a[2])
    return (a[0]/l, a[1]/l, a[2]/l)
def vcross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])
def vdot(a, b): return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]

FWD = vnorm(vsub(CAM_TARGET, CAM_POS))
RIGHT = vnorm(vcross(FWD, (0.0, 1.0, 0.0)))
UP = vnorm(vcross(RIGHT, FWD))
TAN = math.tan(math.radians(FOV_Y) * 0.5)

def cam_ray(nx, ny):
    return vnorm(tuple(FWD[i] + RIGHT[i]*(nx*ASPECT*TAN) + UP[i]*(ny*TAN)
                       for i in range(3)))

probes = []
for name, ndc in (
    ("center", (0.0, 0.0)),
    ("center_left", (-0.4, 0.0)),
    ("center_right", (0.4, 0.0)),
    ("floor_center", (0.0, -0.6)),
    ("floor_left", (-0.6, -0.5)),
    ("ceiling_top", (0.0, 0.8)),
    ("wall_left", (-0.9, 0.0)),
    ("wall_right", (0.9, 0.0)),
    ("interior_opening", (0.15, -0.1)),
    ("mirror_sphere_region", (-0.55, -0.35)),
    ("mirror_box_region", (0.65, -0.4)),
    ("far_corner", (0.85, 0.7)),
):
    d = cam_ray(*ndc)
    h = t4.trace_ray(CAM_POS, d, 10000.0, 0.0)
    probes.append(dict(
        name=name, ndc=ndc, direction=d,
        hit=h["hit"], chart=h["chart"] if h["hit"] else 0,
        distance=h["t"] if h["hit"] else -1.0,
        kind=h["kind"] if h["hit"] else t4.MAT_SKY,
        uv=list(h["uv"]) if h["hit"] else [-1.0, -1.0]))

doc = {
    "schema_version": "reference-final-golden-v1",
    "source": "native display camera + shader_toy/Common.glsl trace semantics",
    "display_policy": {
        "reconstruction": "exact four-bin from completed C0 read view",
        "visible_surface_albedo": True,
        "one_over_pi": False,
        "direct_light": "composited separately per pixel",
        "reflective": "zero (parity kernel)",
        "display_map": "linear"
    },
    "camera": {"position": CAM_POS, "target": CAM_TARGET,
               "forward": FWD, "right": RIGHT, "up": UP,
               "fov_y_degrees": FOV_Y, "aspect": ASPECT},
    "probes": probes,
}
json.dump(doc, open(os.path.join(HERE, "final_golden_v1.json"), "w"), indent=1)

inc = ["// GENERATED by tools/10_refactor/phase7_final/generate_final_golden.py",
       "struct GoldenFinalProbe { const char* name; double ndcx, ndcy; double dx, dy, dz; int hit, chart, kind; double distance, uvx, uvy; };",
       f"static const GoldenFinalProbe kGoldenFinal[{len(probes)}] = {{"]
for p in probes:
    inc.append('  {"%s", %s, %s, %s, %s, %s, %d, %d, %d, %s, %s, %s},' % (
        p["name"], p["ndc"][0], p["ndc"][1], p["direction"][0], p["direction"][1],
        p["direction"][2], 1 if p["hit"] else 0, p["chart"], p["kind"],
        p["distance"], p["uv"][0], p["uv"][1]))
inc.append("};")
open(os.path.abspath(os.path.join(HERE, "../../../src/reference_final_golden.inc")), "w").write(
    "\n".join(inc) + "\n")

print("final probes:", len(probes))
for p in probes:
    print(" %-20s hit=%d chart=%d kind=%d dist=%.4f" % (
        p["name"], p["hit"], p["chart"], p["kind"], p["distance"]))
