#!/usr/bin/env python3
"""Independent Phase 5 G6 upper-merge fixture generator.
Derived from shader_toy/CubeA.glsl:21-41,195-218 and the approved edge
policy (candidate coordinate clamped before both look-back and radiance use).
"""
import json, math, os
PI=3.141592653

def chart(x,y):
    if y<1536:
        if x<256:return 1,(256,256),(0,0),(0,0,0),(1,0,0),(0,0,1)
        if x<512:return 2,(256,256),(256,0),(0,.5,0),(1,0,0),(0,0,1)
        if x<640:return 3,(128,256),(512,0),(0,0,0),(0,1,0),(0,0,1)
        if x<768:return 4,(128,256),(640,0),(1,0,0),(0,1,0),(0,0,1)
        if x<896:return 5,(128,256),(768,0),(0,0,0),(0,1,0),(1,0,0)
        return 6,(128,256),(896,0),(0,0,1),(0,1,0),(1,0,0)
    if x<128:return 7,(128,256),(0,1536),(0,0,.47-1/256),(0,1,0),(1,0,0)
    return 8,(128,256),(128,1536),(0,0,.53-1/256),(0,1,0),(1,0,0)
def add(a,b):return tuple(a[i]+b[i] for i in range(len(a)))
def sub(a,b):return tuple(a[i]-b[i] for i in range(len(a)))
def mul(a,s):return tuple(x*s for x in a)
def dot(a,b):return sum(a[i]*b[i] for i in range(len(a)))
def length(a):return math.sqrt(dot(a,a))
def clamp(x,a,b):return min(max(x,a),b)
def phys(c,p):
    y0=256*c
    if y0<=p[1]<y0+256:return (p[0],p[1]-y0)
    iy=1536+y0
    if iy<=p[1]<iy+256:return (p[0],256+p[1]-iy)
    return (-1,-1)
def merge_fixture(name,uv,alphas,colors,local=(.1,.2,.3),distance=.02):
    cid,g,b,gpos,gt,gb=chart(*uv); c=int((uv[1]%1536)//256); S=2**(c+1); SU=2*S
    mod=(uv[0]%g[0],uv[1]%g[1]); pp=(g[0]/S,g[1]/S); uvo=(pp[0]/2,pp[1]/2)
    probe=add(gpos,add(mul(gt,(mod[0]%pp[0])*S/256),mul(gb,(mod[1]%pp[1])*S/256)))
    origin=(math.floor(uv[0]/g[0])*g[0],math.floor(uv[1]/g[1])*g[1]+g[1])
    dirs=(math.floor(mod[0]/pp[0])*pp[0],math.floor(mod[1]/pp[1])*pp[1])
    p=(clamp((mod[0]%pp[0])*.5,.5,uvo[0]-.5),clamp((mod[1]%pp[1])*.5,.5,uvo[1]-.5))
    f=(p[0]-.5-math.floor(p[0]-.5),p[1]-.5-math.floor(p[1]-.5)); base=(math.floor(p[0]-.5)+.5,math.floor(p[1]-.5)+.5)
    offs=((0,0),(1,0),(0,1),(1,1)); weights=((1-f[0])*(1-f[1]),f[0]*(1-f[1]),(1-f[0])*f[1],f[0]*f[1])
    candidates=[]; numerator=[0,0,0]; vw=0
    for i,o in enumerate(offs):
        q=(clamp(base[0]+o[0],.5,uvo[0]-.5),clamp(base[1]+o[1],.5,uvo[1]-.5))
        wp=add(gpos,add(mul(gt,q[0]*SU/256),mul(gb,q[1]*SU/256))); rel=sub(probe,wp)
        theta=(SU*.5-.5)/(SU*.5)*PI*.5; phi=math.atan2(-dot(rel,gt),-dot(rel,gb)); count=4+8*(SU*.5-1)
        phiI=math.floor((phi/PI*.5+.5)*count)+.5; L=SU-1
        if phiI<L:pu=(SU-.5,SU-phiI)
        elif phiI<L*2:pu=(SU-(phiI-L),.5)
        elif phiI<L*3:pu=(.5,phiI-L*2)
        else:pu=(phiI-L*3,SU-.5)
        look=(origin[0]+dirs[0]+math.floor(pu[0])*uvo[0]+q[0],origin[1]+dirs[1]+math.floor(pu[1])*uvo[1]+q[1])
        rb=(origin[0]+dirs[0]+q[0],origin[1]+dirs[1]+q[1]); ros=((0,0),(uvo[0],0),(0,uvo[1]),uvo)
        rads=[add(rb,x) for x in ros]; vis=alphas[i]<-.5 or length(rel)<alphas[i]*math.cos(PI*.5-theta)+.01
        rs=tuple(colors[i][k]*4 for k in range(3))
        if vis:
            vw+=weights[i]
            for k in range(3):numerator[k]+=rs[k]*weights[i]
        candidates.append(dict(q=q,weight=weights[i],world=wp,lookBackGlobal=look,lookBackPhysical=phys(c+1,look),alpha=alphas[i],visible=vis,radianceGlobal=rads,radiancePhysical=[phys(c+1,x) for x in rads],radianceSum=rs))
    upper=tuple(x/max(.01,vw) for x in numerator); baseT=(1/256)*S*1.5; mn=0 if c==0 else baseT; inter=baseT*2 if c==0 else baseT
    l=1-clamp((distance-mn)/inter,0,1); merged=tuple(local[k]*l+upper[k]*(1-l) for k in range(3))
    return dict(name=name,uv=uv,cascade=c,probeSize=S,upperCascade=c+1,localRgb=local,localAlpha=distance,traceDistance=distance,fraction=f,candidates=candidates,visibleWeight=vw,upperRgb=upper,localWeight=l,mergedRgb=merged,mergedAlpha=distance)

fixtures=[
 merge_fixture('floor_c0_all_visible',(73.5,91.5),[-1,-1,-1,-1],[(.2,.4,.6)]*4,distance=3/256),
 merge_fixture('floor_c0_one_visible',(73.5,91.5),[-1,-.4,-.4,-.4],[(1,0,0)]*4,distance=6/256),
 merge_fixture('floor_c0_none_visible',(73.5,91.5),[-.4,-.4,-.4,-.4],[(9,8,7)]*4,distance=6/256),
 merge_fixture('floor_c0_edge_clamped',(255.5,255.5),[-1,-1,-1,-1],[(1,2,3)]*4,distance=6/256),
 merge_fixture('interior_c1_mixed',(170.5,1870.5),[-1,-.4,-1,-.4],[(.2,.1,.3)]*4,distance=.04),
]
doc={'schema_version':'reference-upper-merge-golden-v1','source':'shader_toy/CubeA.glsl:21-41,195-218','edge_policy':'clamp candidate before look-back and radiance addressing','sampler':'nearest integer texel fetch; distance alpha from look-back address only','fixtures':fixtures}
here=os.path.dirname(os.path.abspath(__file__));json.dump(doc,open(os.path.join(here,'merge_golden_v1.json'),'w'),indent=1)
inc=['// GENERATED by tools/10_refactor/phase5_merge/generate_merge_golden.py','struct GoldenMergeFixture { const char* name; double uvx,uvy,lr,lg,lb,distance,ur,ug,ub,localWeight,mr,mg,mb,alpha,visibleWeight; int cascade; };',f'static const GoldenMergeFixture kGoldenMerge[{len(fixtures)}] = {{']
for x in fixtures: inc.append('  {"%s", %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %d},' % (x['name'],x['uv'][0],x['uv'][1],x['localRgb'][0],x['localRgb'][1],x['localRgb'][2],x['traceDistance'],x['upperRgb'][0],x['upperRgb'][1],x['upperRgb'][2],x['localWeight'],x['mergedRgb'][0],x['mergedRgb'][1],x['mergedRgb'][2],x['mergedAlpha'],x['visibleWeight'],x['cascade']))
inc.append('};')
open(os.path.abspath(os.path.join(here,'../../../src/reference_merge_golden.inc')),'w').write('\n'.join(inc)+'\n')
print('fixtures',len(fixtures))
