#!/usr/bin/env python3
"""Independent Phase 6 G7 feedback-address fixtures.
Derived from CubeA.glsl:166-170: the exact four previous-frame C0 direction
bins reconstructed from hit chart and hit UV.
"""
import json, math, os

CHARTS = {
    1: dict(name="floor",     res=(256,256), base=(0,0)),
    2: dict(name="ceiling",   res=(256,256), base=(256,0)),
    3: dict(name="wall_x0",   res=(128,256), base=(512,0)),
    4: dict(name="wall_x1",   res=(128,256), base=(640,0)),
    5: dict(name="wall_z0",   res=(128,256), base=(768,0)),
    6: dict(name="wall_z1",   res=(128,256), base=(896,0)),
    7: dict(name="int_front", res=(128,256), base=(0,1536)),
    8: dict(name="int_back",  res=(128,256), base=(128,1536)),
}

def clamp(x, a, b): return min(max(x, a), b)

def phys_c0(p):
    # cascade 0 mapping: primary band y in [0,256), interior y in [1536,1792)
    if 0.0 <= p[1] < 256.0: return (p[0], p[1])
    if 1536.0 <= p[1] < 1792.0: return (p[0], p[1] - 1280.0)
    return (-1, -1)

fixtures = []
for chart_id, ch in CHARTS.items():
    res = ch["res"]
    half = (res[0] / 2.0, res[1] / 2.0)
    for uv, tag in (((0.25, 0.5), "mid"), ((0.001, 0.999), "edge_min"), ((0.999, 0.001), "edge_max")):
        suv_local = (clamp(uv[0] * half[0], 0.5, half[0] - 0.5),
                     clamp(uv[1] * half[1], 0.5, half[1] - 0.5))
        suv = (suv_local[0] + ch["base"][0], suv_local[1] + ch["base"][1])
        bins = [suv,
                (suv[0] + half[0], suv[1]),
                (suv[0], suv[1] + half[1]),
                (suv[0] + half[0], suv[1] + half[1])]
        fixtures.append(dict(
            name=f"{ch['name']}_{tag}", chartId=chart_id, chartUv=uv,
            suv=suv, binsGlobal=bins, binsPhysical=[phys_c0(b) for b in bins]))

doc = {
    "schema_version": "reference-feedback-golden-v1",
    "source": "shader_toy/CubeA.glsl:166-170",
    "semantics": "sum of the exact four previous-generation C0 direction bins; clamp before adding chart base; cascade-0 physical mapping",
    "fixtures": fixtures,
}
here = os.path.dirname(os.path.abspath(__file__))
json.dump(doc, open(os.path.join(here, "feedback_golden_v1.json"), "w"), indent=1)

inc = ["// GENERATED by tools/10_refactor/phase6_feedback/generate_feedback_golden.py",
       "struct GoldenFeedbackFixture { const char* name; int chartId; double uvx, uvy; double suvX, suvY; double bins[4][2]; double phys[4][2]; };",
       f"static const GoldenFeedbackFixture kGoldenFeedback[{len(fixtures)}] = {{"]
for x in fixtures:
    b = ", ".join("{%s, %s}" % (v[0], v[1]) for v in x["binsGlobal"])
    p = ", ".join("{%s, %s}" % (v[0], v[1]) for v in x["binsPhysical"])
    inc.append('  {"%s", %d, %s, %s, %s, %s, {%s}, {%s}},' % (
        x["name"], x["chartId"], x["chartUv"][0], x["chartUv"][1],
        x["suv"][0], x["suv"][1], b, p))
inc.append("};")
open(os.path.abspath(os.path.join(here, "../../../src/reference_feedback_golden.inc")), "w").write("\n".join(inc) + "\n")
print("feedback fixtures:", len(fixtures))
